version: '3'

services:
  nginx:
    image: nginx:1.15.7-alpine
    container_name: ramona_nginx
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_EXPOSED_PORT:-0}:80
    working_dir: /app
    restart: always
    depends_on:
      - php

  php:
    build: ./docker/php/fpm
    image: ramona_php
    container_name: ramona_php
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:5.0-alpine3.8
    container_name: ramona_redis
    restart: always
    ports:
      - ${REDIS_EXPOSED_PORT:-0}:6379

  mysql:
    image: mysql:5.7.27
    container_name: ramona_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
